[package]
name = "plotting_egui"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
csv.workspace = true
eframe.workspace = true
egui_plot.workspace = true
inquire.workspace = true