[package]
name = "aerospace"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
ndarray = { version = "0.16.1", features = ["approx"] }
matfile = { version = "0.4.1", features = ["ndarray"] }