[package]
name = "aerospace"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
serde = "1.0.136"
serde_json = "1.0.79"
rotations = {path = "../rotations"}
approx_eq = "0.1.8"

ndarray = { version = "0.16.1", features = ["approx"] }
matfile = { version = "0.4.1", features = ["ndarray"] }
csv = "1.3.0"
