[package]
name = "aerospace"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra.workspace = true
serde.workspace = true
rotations.workspace = true
spice.workspace = true
time.workspace = true
approx.workspace = true
interp.workspace = true
thiserror.workspace = true
