[package]
name = "nadir_egui_plots"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true