[package]
name = "gpu_surface_area"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck.workspace = true
glam.workspace = true
wgpu.workspace = true
nadir_3d.workspace = true
