[package]
name = "nadir_fsw"
version = "0.1.0"
edition = "2021"

[dependencies]
multibody.workspace = true
nalgebra.workspace = true
serde.workspace = true
thiserror.workspace = true
transforms.workspace = true
