[package]
name = "nadir_fsw"
version = "0.1.0"
edition = "2021"

[dependencies]
multibody = {path = "../multibody"}
nalgebra = "0.33.2"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
transforms = {path = "../transforms"}
