[package]
name = "gdt"
version = "0.1.0"
edition = "2021"

[workspace]
members = [    
    "coordinate_systems",
    "linear_algebra",
    "multibody",
    "rotations", "sim_value",
    "transforms",    
]

[dependencies]
coordinate_systems = {path = "./coordinate_systems"}
multibody = { path = "./multibody" }
rotations = { path = "./rotations" }
transforms = { path = "./transforms" }
