[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Jonathan Davis <jonathan.p.davis.@nasa.gov>"]
rust-version = "1.82.0"

[workspace]
members = [ 
    "aerospace", 
    "benchmarks", 
    "color", 
    "coordinate_systems",     
    "examples/*",
    "mass_properties",
    "multibody", 
    "nadir",    
    "nadir_3d", 
    "nadir_animation", 
    "nadir_fsw",    
    "rotations", 
    "spatial_algebra",
    "spice", 
    "transforms", 
    "utilities",
    "time", 
]
resolver = "2"

[workspace.dependencies]
aerospace = {path = "aerospace"} 
color  = {path = "color"}  
coordinate_systems  = {path = "coordinate_systems"}
mass_properties = {path = "mass_properties"} 
multibody = {path = "multibody"}  
nadir = {path = "nadir"}  
nadir_animation = {path = "nadir_animation"}   
nadir_3d = {path = "nadir_3d"}  
nadir_fsw = {path = "nadir_fsw"} 
rotations = {path = "rotations"} 
spatial_algebra = {path = "spatial_algebra"} 
spice = {path = "spice"} 
transforms = {path = "transforms"} 
utilities = {path = "utilities"} 
time = {path = "time"} 
clap = "4.5.21"
nalgebra = "0.33.2"
ron = "0.8.1"


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 0

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 0

[profile.release]
debug = 0
opt-level = 2       # Optimizes for binary size. Use "3" for max performance.
lto = "off"          # Link Time Optimization. "fat" can be more aggressive but slower to compile.
panic = 'abort'       # Reduces binary size by not including unwind code.
incremental = true   # Disables incremental compilation for release builds.

