[workspace]
members = [ "aerospace", "gadgt_animation", "benchmarks", "gadgt",    
    "coordinate_systems", "differential_equations", "mass_properties",
    "multibody", 
    "rotations", "sim_value", "spatial_algebra",
    "transforms", "utilities", "color", "gadgt_3d",    
]
resolver = "2"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 0

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 0

[profile.release]
debug = 1
opt-level = 3       # Optimizes for binary size. Use "3" for max performance.
lto = "thin"          # Link Time Optimization. "fat" can be more aggressive but slower to compile.
codegen-units = 1     # Better optimization across the entire crate but slower compilation.
panic = 'abort'       # Reduces binary size by not including unwind code.
incremental = false   # Disables incremental compilation for release builds.
