[package]
name = "gdt"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "benchmarks",    
    "coordinate_systems", "differential_equations",
    "linear_algebra", "mass_properties",
    "multibody", "plotting",
    "rotations", "sim_value", "spatial_algebra",
    "transforms", "utilities",    
]

[dependencies]
coordinate_systems = {path = "./coordinate_systems"}
differential_equations = {path = "./differential_equations"}
mass_properties = {path = "./mass_properties"}
multibody = { path = "./multibody" }
plotting = {path = "./plotting"}
rotations = { path = "./rotations" }
transforms = { path = "./transforms" }

