[package]
name = "gdt"
version = "0.1.0"
edition = "2021"

[workspace]
members = [    
    "coordinate_systems",
    "linear_algebra", "mass_properties",
    "multibody",
    "rotations", "sim_value", "spatial_algebra",
    "transforms", "utilities",    
]

[dependencies]
coordinate_systems = {path = "./coordinate_systems"}
multibody = { path = "./multibody" }
rotations = { path = "./rotations" }
transforms = { path = "./transforms" }
mass_properties = {path = "./mass_properties"}
