# .rustfmt.toml
max_width = 100
use_small_heuristics = "Off"

# Force method chains to break
chain_width = 1               # This will make .with_distribution() go to next line

# But allow function calls to stay on one line if they're short
fn_call_width = 30            # Let Normal::new(1.0, 0.1) stay on one line 

# Control struct literals behavior
struct_lit_width = 60         # Adjust based on your preference for struct literals