[package]
name = "spherical_harmonics"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
legendre.workspace = true
thiserror.workspace = true