[package]
name = "spherical_harmonics"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
coordinate_systems.workspace = true
legendre.workspace = true
nalgebra.workspace = true
thiserror.workspace = true