[package]
name = "multibody"
version = "0.1.0"
edition = "2021"

[dependencies]
sim_value = {path = "../sim_value"}
transforms = {path = "../transforms"}
coordinate_systems = {path = "../coordinate_systems"}
linear_algebra = {path = "../linear_algebra"}
rotations = {path = "../rotations"}
spatial_algebra = {path = "../spatial_algebra"}
mass_properties = {path = "../mass_properties"}