[package]
name = "multibody"
version = "0.1.0"
edition = "2021"

[dependencies]
sim_value = {path = "../sim_value"}
transforms = {path = "../transforms"}
coordinate_systems = {path = "../coordinate_systems"}
rotations = {path = "../rotations"}
