[package]
name = "gravity"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
approx.workspace = true
nalgebra.workspace = true
utilities.workspace = true