[package]
name = "nadir_fsw"
version.workspace = true
edition.workspace = true

[dependencies]
multibody.workspace = true
nalgebra.workspace = true
serde.workspace = true
thiserror.workspace = true
transforms.workspace = true
