[package]
name = "spice"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
phf = { version = "0.11.2", features = ["macros"] }
serde = { version = "1.0.210", features = ["derive"] }
