[package]
name = "rotations"
version = "0.1.0"
edition = "2021"

[dependencies]
approx.workspace = true
coordinate_systems.workspace = true
nalgebra.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
