[package]
name = "rotations"
version.workspace = true
edition.workspace = true

[dependencies]
approx.workspace = true
coordinate_systems.workspace = true
nalgebra.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
