[package]
name = "rotations"
version = "0.1.0"
edition = "2021"

[dependencies]
approx_eq = "0.1.8"
coordinate_systems = {path = "../coordinate_systems"}
nalgebra = "0.33.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
