[package]
name = "nadir_3d"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
color.workspace = true
glam.workspace = true
iced.workspace = true
serde.workspace = true
thiserror.workspace = true