WHITESPACE = _{ " " | "\t" | NEWLINE }

primary = _{ enclosed | struct_call | instance_call | instance_field | function_call | matrix | vector | identifier | number }
term = _{ prefix }
prefix = { neg* ~ postfix }
neg = { "-" }
postfix = { primary ~ fac* }
fac = { "!" }
pow = { "^" }
exponential = { term ~ ( pow ~ term )? }
multiplicative = { exponential ~ ( (mul | div) ~ exponential )* }
mul = { "*" }
div = { "/" }
additive = { multiplicative ~ ( (add | sub) ~ multiplicative )* }
add = { "+" }
sub = { "-" }
expr = _{ 
    &(primary ~ EOI) ~ primary 
    | additive
}

assignment = { identifier ~ "=" ~ expr }

identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
integer = @{ "-"? ~ ASCII_DIGIT+ }
float = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ ~ (("e" | "E") ~ ("+" | "-")? ~ ASCII_DIGIT+)? }
number = _{ float | integer }
enclosed = _{ "(" ~ expr ~ ")" }

comma_separated = _{ expr ~ ( "," ~ expr)* }
space_separated = ${ expr ~ (SPACE_SEPARATOR+ ~ expr)* }

function_call = { identifier ~ "(" ~ arguments? ~ ")" }
arguments = { comma_separated }

struct_call = { identifier ~ "::" ~ function_call}
instance_field = { identifier ~ "." ~ identifier }
instance_call = { identifier ~ "." ~ function_call}

line = { silent_line | print_line }
silent_line = { (assignment | expr) ~ ";" }
print_line = { assignment | expr }

elements = { comma_separated }
vector = { "[" ~ (elements)? ~ "]" }
matrix_row = { space_separated }
matrix = { "[" ~ matrix_row ~ ( ";" ~ matrix_row )* ~ "]" }