WHITESPACE = _{ " " | "\t" | NEWLINE }

math_expr = { prefix* ~ term ~ postfix* ~ (infix ~ prefix* ~ term ~ postfix*)* }
term = { enclosed | struct_call | function_call | identifier | number }

infix = _{ add | sub | mul | div }
add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }
pow = { "^" } // Exponentiation

prefix = _{ neg }
neg = { "-" }

postfix = _{ fac }
fac = { "!" }

identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
integer = @{ "-"? ~ ASCII_DIGIT+ }
float = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ ~ (("e" | "E") ~ ("+" | "-")? ~ ASCII_DIGIT+)? }
number = { float | integer }

enclosed = { "(" ~ WHITESPACE* ~ math_expr ~ WHITESPACE* ~ ")" }

assignment = { identifier ~ WHITESPACE* ~ "=" ~ WHITESPACE* ~ math_expr }

function_call = { identifier ~ "(" ~ WHITESPACE* ~ function_arguments? ~ WHITESPACE* ~ ")" }
function_arguments = { math_expr ~ (WHITESPACE* ~ "," ~ WHITESPACE* ~ math_expr)* }

struct_call = { identifier ~ "::" ~ function_call}

line = { silent_line* ~ (print_line | silent_line) }
silent_line = { print_line ~ ";" }
print_line = { assignment | math_expr }
