[package]
name = "nadir_diffeq"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
celestial.workspace = true
csv.workspace = true
aerospace.workspace = true
tolerance.workspace = true
time.workspace = true
