[package]
name = "nadir_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
