[package]
name = "transforms"
version = "0.1.0"
edition = "2021"

[dependencies]
coordinate_systems = {path = "../coordinate_systems"}
linear_algebra = {path = "../linear_algebra"}
rotations = {path = "../rotations"}
sim_value = {path = "../sim_value"}
approx = "0.5.1"
approx_eq = "0.1.8"
