[package]
name = "transforms"
version.workspace = true
edition.workspace = true

[dependencies]
coordinate_systems.workspace = true
rotations.workspace = true
mass_properties.workspace = true
approx.workspace = true
nalgebra.workspace = true
serde.workspace = true
