[package]
name = "time"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.65"
