[package]
name = "gadgt_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.17.1", features = ["derive"] }
color = {path = "../color"}
glam = { version = "0.29.0", features = ["bytemuck", "serde"] }
iced = "0.12.1"
serde = { version = "1.0.209", features = ["derive"] }
