[package]
name = "spatial_algebra"
version = "0.1.0"
edition = "2021"

[dependencies]
coordinate_systems.workspace = true
rotations.workspace = true
transforms.workspace = true
mass_properties.workspace = true
nalgebra.workspace = true
serde.workspace = true
approx.workspace = true
