[package]
name = "legendre"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
utilities.workspace = true
thiserror.workspace = true