[package]
name = "mass_properties"
version.workspace = true
edition.workspace = true

[dependencies]
nalgebra.workspace = true
rand.workspace = true
rand_distr.workspace = true
serde.workspace = true
thiserror.workspace = true
uncertainty.workspace = true