[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
criterion = "0.5.1"
mass_properties = {path = "../mass_properties"}
nalgebra = "0.33.0"
uuid = { version = "1.10.0", features = ["v4"] }

[[bench]]
name = "vec_vs_hashmap_lookup"
harness = false
