[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
criterion = "0.5.1"
mass_properties = {path = "../mass_properties"}

[[bench]]
name = "arrayvec_vs_vec"
harness = false
